# Generated by Django 5.2.1 on 2025-11-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yksshop', '0005_product_image_url_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
