# Generated by Django 5.2.1 on 2025-11-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yksshop', '0006_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
