# Generated by Django 5.2.1 on 2025-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yksshop', '0009_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Premium Men's Wear Collection", max_length=150)),
                ('subtitle', models.CharField(default='Discover the latest styles and timeless classics', max_length=255)),
                ('primary_button_label', models.CharField(default='Shop the Collection', max_length=80)),
                ('primary_button_url', models.CharField(default='/shop/', max_length=200)),
                ('secondary_button_label', models.CharField(blank=True, max_length=80, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero Content',
                'verbose_name_plural': 'Homepage Hero Content',
            },
        ),
    ]
